import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { createHash } from 'crypto';

const prod = process.argv.includes('--prod');
const watch = process.argv.includes('--watch');

// ── Service-worker generation ──────────────────────────────────────────
// Walk the deliverable assets and bake a precache list + content-hash
// version into sw.js so the PWA installs and runs fully offline.
function generateServiceWorker() {
  const include = ['assets', 'fonts', 'icons'];
  const files = ['./', './index.html', './friedzooki.bundle.js',
                 './theme.css', './manifest.webmanifest'];
  const walk = dir => {
    for (const name of readdirSync(dir)) {
      const p = `${dir}/${name}`;
      if (statSync(p).isDirectory()) walk(p);
      else files.push('./' + p);
    }
  };
  include.forEach(walk);

  // Version = hash of bundle + theme so clients refresh when code changes.
  const h = createHash('sha1');
  h.update(readFileSync('friedzooki.bundle.js'));
  h.update(readFileSync('theme.css'));
  const version = h.digest('hex').slice(0, 10);

  const sw = `// Auto-generated by build.js — do not edit by hand.
const CACHE = 'friedzooki-${version}';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Navigations: network-first, fall back to cached shell (offline).
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('./index.html')));
    return;
  }

  // Everything else: cache-first, fill cache on miss.
  // ignoreSearch so versioned ?v= query strings still hit the precache.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }))
  );
});
`;
  writeFileSync('sw.js', sw);
  console.log(`✓ generated sw.js (friedzooki-${version}, ${files.length} files precached)`);
}

const ctx = await esbuild.context({
  entryPoints: ['src/main.js'],
  bundle: true,
  outfile: 'friedzooki.bundle.js',
  loader: { '.wasm': 'dataurl' },
  format: 'iife',
  platform: 'browser',
  target: ['chrome90', 'safari14', 'firefox88'],
  minify: prod,
  sourcemap: !prod,
  define: {
    'process.env.NODE_ENV': prod ? '"production"' : '"development"'
  },
  logLevel: 'info',
});

if (watch) {
  await ctx.watch();
  console.log('watching...');
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log('✓ built friedzooki.bundle.js');
  generateServiceWorker();
}
