// Auto-generated by build.js — do not edit by hand.
const CACHE = 'friedzooki-95c7da9560';
const PRECACHE = [
  "./",
  "./index.html",
  "./friedzooki.bundle.js",
  "./theme.css",
  "./manifest.webmanifest",
  "./assets/btn-back.png",
  "./assets/btn-check.png",
  "./assets/contests/assault.png",
  "./assets/contests/ball.png",
  "./assets/contests/blockpush.png",
  "./assets/contests/china.png",
  "./assets/contests/dodge.png",
  "./assets/contests/hurdles.png",
  "./assets/contests/marbles.png",
  "./assets/contests/merry.png",
  "./assets/contests/ramps.png",
  "./assets/contests/smash.png",
  "./assets/contests/sprint.png",
  "./assets/contests/steps.png",
  "./assets/contests/sumo.png",
  "./assets/contests/tag.png",
  "./assets/contests/weakest.png",
  "./assets/contests/zigzag.png",
  "./assets/skins/bark.png",
  "./assets/skins/bear.png",
  "./assets/skins/brain.png",
  "./assets/skins/chameleon.png",
  "./assets/skins/cheetah.png",
  "./assets/skins/chequer.png",
  "./assets/skins/circuit.png",
  "./assets/skins/crystal.png",
  "./assets/skins/elephant.png",
  "./assets/skins/fishscales.png",
  "./assets/skins/giraffe.png",
  "./assets/skins/ice.png",
  "./assets/skins/lava.png",
  "./assets/skins/leopard.png",
  "./assets/skins/metal.png",
  "./assets/skins/rust.png",
  "./assets/skins/slime.png",
  "./assets/skins/snakeskin.png",
  "./assets/skins/spots.png",
  "./assets/skins/stripes.png",
  "./assets/skins/tiger.png",
  "./assets/skins/zebra.png",
  "./assets/title-friedzooki.png",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Navigations: network-first, fall back to cached shell (offline).
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('./index.html')));
    return;
  }

  // Everything else: cache-first, fill cache on miss.
  // ignoreSearch so versioned ?v= query strings still hit the precache.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }))
  );
});
