// Auto-generated by build.js — do not edit by hand.
const CACHE = 'friedzooki-2b986401b5';
const PRECACHE = [
  "./",
  "./index.html",
  "./friedzooki.bundle.js",
  "./theme.css",
  "./manifest.webmanifest",
  "./assets/blob-idea-green.png",
  "./assets/blob-idea-green2.png",
  "./assets/blob-idea-red.png",
  "./assets/blob-idea-yellow.png",
  "./assets/blob-yellow.png",
  "./assets/btn-back.png",
  "./assets/btn-check.png",
  "./assets/btn-close.png",
  "./assets/bubble-keyword.png",
  "./assets/bubble-keyword2.png",
  "./assets/bubble-large.png",
  "./assets/bubble-pink.png",
  "./assets/frame-dashed.png",
  "./assets/frame-green.png",
  "./assets/icon-cassette.png",
  "./assets/icon-eye.png",
  "./assets/icon-link.png",
  "./assets/lilypad.png",
  "./assets/line-dotted.png",
  "./assets/line-dotted2.png",
  "./assets/modal-large.png",
  "./assets/modal-small.png",
  "./assets/shell-dashed.png",
  "./assets/slider-track.png",
  "./assets/tab-library.png",
  "./assets/tab-zook.png",
  "./assets/text-field.png",
  "./assets/voice/build_0.ogg",
  "./assets/voice/build_1.ogg",
  "./assets/voice/build_2.ogg",
  "./assets/voice/champion_0.ogg",
  "./assets/voice/champion_1.ogg",
  "./assets/voice/coach_legs_0.ogg",
  "./assets/voice/coach_power_0.ogg",
  "./assets/voice/coach_stride_0.ogg",
  "./assets/voice/collision_0.ogg",
  "./assets/voice/collision_1.ogg",
  "./assets/voice/intro_0.ogg",
  "./assets/voice/intro_1.ogg",
  "./assets/voice/lead_change_0.ogg",
  "./assets/voice/lead_change_1.ogg",
  "./assets/voice/lead_change_2.ogg",
  "./assets/voice/lose_0.ogg",
  "./assets/voice/lose_1.ogg",
  "./assets/voice/lose_2.ogg",
  "./assets/voice/manifest.json",
  "./assets/voice/new_record_0.ogg",
  "./assets/voice/new_record_1.ogg",
  "./assets/voice/race_start_0.ogg",
  "./assets/voice/race_start_1.ogg",
  "./assets/voice/race_start_2.ogg",
  "./assets/voice/save_0.ogg",
  "./assets/voice/save_1.ogg",
  "./assets/voice/title_0.ogg",
  "./assets/voice/title_1.ogg",
  "./assets/voice/win_0.ogg",
  "./assets/voice/win_1.ogg",
  "./assets/voice/win_2.ogg",
  "./fonts/fredoka-one.ttf",
  "./fonts/patrick-hand.ttf",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Navigations: network-first, fall back to cached shell (offline).
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('./index.html')));
    return;
  }

  // Everything else: cache-first, fill cache on miss.
  // ignoreSearch so versioned ?v= query strings still hit the precache.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
      if (res && res.status === 200 && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }))
  );
});
